package pet.park.entity;

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Embedded;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.ManyToOne;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

@Entity
@Data
public class PetPark {
	// set petParkId as PK and autogenerated
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long petParkId;

	private String parkName;
	private String directions;
	private String stateOrProvince;
	private String country;

	@Embedded
	private GeoLocation geoLocation;

	// many to one relationship with Contributor with on delete cascade
	// specify join column in snake case and not null
	@EqualsAndHashCode.Exclude
	@ToString.Exclude
	@ManyToOne(cascade = CascadeType.ALL)
	@JoinColumn(name = "contributor_id", nullable = false)
	private Contributor contributor;

	// many to many relationship with amenity with on delete persist
	// Delete will remove PetPark row but leave Amenity rows.
	@EqualsAndHashCode.Exclude
	@ToString.Exclude
	@ManyToMany(cascade = CascadeType.PERSIST)
	@JoinTable(name = "pet_park_amenity",
		joinColumns = @JoinColumn(name = "pet_park_id)"),
		inverseJoinColumns = @JoinColumn(name = "amenity_id"))
	private Set<Amenity> amenities = new HashSet<>();

} // end CLASS
